
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

# 设置默认目标 cargo build  
[build]
target = "x86_64-blog_os.json"

# 配置此项后,通过cargo run即可以编译内核,并且在qemu中运行
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
